services:
  frontend:
    build:
      context: .
      args:
        API_BASE_URL: ${API_BASE_URL}
        FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
        FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    ports:
      - "8080:80"
    networks:
      - front-end
    environment:
      - NODE_ENV=production
      - DOMAIN=${LOCAL_IP}
    restart: always

  lb:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
    networks:
      - front-end 

networks:
  front-end:
    driver: bridge
